# Generated by Django 5.2.17 on 2026-08-19 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eyebrow", models.CharField(default="OUR STORY", max_length=80)),
                (
                    "title",
                    models.CharField(
                        default="A Sanctuary for Movement & Mindfulness", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="Founded with a passion for holistic wellbeing, AURELIA brings together the ancient discipline of yoga and the electrifying energy of Zumba under one roof. Our state-of-the-art studio is designed to help you build strength, flexibility and calm — guided every step of the way by certified, internationally trained instructors in a warm, welcoming community."
                    ),
                ),
                (
                    "image_1",
                    models.ImageField(blank=True, null=True, upload_to="about/"),
                ),
                (
                    "image_1_url",
                    models.URLField(
                        blank=True,
                        default="https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?q=80&w=1000&auto=format&fit=crop",
                        max_length=500,
                    ),
                ),
                (
                    "image_2",
                    models.ImageField(blank=True, null=True, upload_to="about/"),
                ),
                (
                    "image_2_url",
                    models.URLField(
                        blank=True,
                        default="https://images.unsplash.com/photo-1518611012118-696072aa579a?q=80&w=1000&auto=format&fit=crop",
                        max_length=500,
                    ),
                ),
                (
                    "image_3",
                    models.ImageField(blank=True, null=True, upload_to="about/"),
                ),
                (
                    "image_3_url",
                    models.URLField(
                        blank=True,
                        default="https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?q=80&w=1000&auto=format&fit=crop",
                        max_length=500,
                    ),
                ),
                ("years_experience", models.PositiveIntegerField(default=12)),
                ("happy_members", models.PositiveIntegerField(default=3200)),
                ("certified_trainers", models.PositiveIntegerField(default=18)),
                (
                    "success_rate",
                    models.PositiveIntegerField(
                        default=98, help_text="Positive results, shown as a percentage"
                    ),
                ),
            ],
            options={
                "verbose_name": "About Section",
                "verbose_name_plural": "About Section",
            },
        ),
        migrations.CreateModel(
            name="CTASection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Your Wellness Journey Starts Today.", max_length=200
                    ),
                ),
                (
                    "subtitle",
                    models.TextField(
                        default="Take the first step towards a stronger, calmer, healthier you. Book your free trial class now."
                    ),
                ),
                (
                    "background_image",
                    models.ImageField(blank=True, null=True, upload_to="cta/"),
                ),
                (
                    "background_image_url",
                    models.URLField(
                        blank=True,
                        default="https://images.unsplash.com/photo-1552196563-55cd4e45efb3?q=80&w=1920&auto=format&fit=crop",
                        max_length=500,
                    ),
                ),
                (
                    "background_video",
                    models.FileField(blank=True, null=True, upload_to="cta/videos/"),
                ),
                ("background_video_url", models.URLField(blank=True, max_length=500)),
                (
                    "primary_button_text",
                    models.CharField(default="Book Free Trial", max_length=60),
                ),
                (
                    "primary_button_link",
                    models.CharField(default="#contact", max_length=120),
                ),
            ],
            options={
                "verbose_name": "Call To Action Section",
                "verbose_name_plural": "Call To Action Section",
            },
        ),
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=30)),
                (
                    "program_interested",
                    models.CharField(
                        blank=True, default="General Enquiry", max_length=150
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Enquiry",
                "verbose_name_plural": "Enquiries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GalleryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")],
                        default="image",
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("studio", "Studio"),
                            ("yoga", "Yoga Session"),
                            ("zumba", "Zumba Session"),
                            ("event", "Event"),
                        ],
                        default="studio",
                        max_length=20,
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=180)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="gallery/images/"
                    ),
                ),
                ("image_url", models.URLField(blank=True, max_length=500)),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to="gallery/videos/"
                    ),
                ),
                ("video_url", models.URLField(blank=True, max_length=500)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="gallery/thumbs/"
                    ),
                ),
                ("thumbnail_url", models.URLField(blank=True, max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Gallery Item",
                "verbose_name_plural": "Studio Gallery",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HeroContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "headline",
                    models.CharField(
                        default="Move Your Body. Elevate Your Energy.", max_length=200
                    ),
                ),
                (
                    "subtitle",
                    models.TextField(
                        default="Premium yoga, energetic Zumba and holistic wellness programs designed by certified experts to transform your mind, body and spirit."
                    ),
                ),
                (
                    "background_video",
                    models.FileField(blank=True, null=True, upload_to="hero/videos/"),
                ),
                (
                    "background_video_url",
                    models.URLField(
                        blank=True,
                        default="https://cdn.coverr.co/videos/coverr-yoga-practice-at-sunrise-2633/1080p.mp4",
                        max_length=500,
                    ),
                ),
                (
                    "poster_image",
                    models.ImageField(blank=True, null=True, upload_to="hero/"),
                ),
                (
                    "poster_image_url",
                    models.URLField(
                        blank=True,
                        default="https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?q=80&w=1920&auto=format&fit=crop",
                        max_length=500,
                    ),
                ),
                (
                    "primary_cta_text",
                    models.CharField(default="Book a Free Trial", max_length=60),
                ),
                (
                    "primary_cta_link",
                    models.CharField(default="#contact", max_length=120),
                ),
                (
                    "secondary_cta_text",
                    models.CharField(default="Explore Classes", max_length=60),
                ),
                (
                    "secondary_cta_link",
                    models.CharField(default="#yoga-programs", max_length=120),
                ),
            ],
            options={
                "verbose_name": "Hero Section",
                "verbose_name_plural": "Hero Section",
            },
        ),
        migrations.CreateModel(
            name="HeroStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("heart-pulse", "Heart Pulse"),
                            ("flower-2", "Flower"),
                            ("users", "Users"),
                            ("clock", "Clock"),
                            ("award", "Award"),
                            ("smile", "Smile"),
                            ("sparkles", "Sparkles"),
                            ("shield-check", "Shield Check"),
                            ("dumbbell", "Dumbbell"),
                            ("music-4", "Music"),
                            ("sun", "Sun"),
                            ("leaf", "Leaf"),
                            ("trophy", "Trophy"),
                            ("badge-check", "Badge Check"),
                            ("calendar-check", "Calendar Check"),
                            ("gem", "Gem"),
                            ("target", "Target"),
                            ("wallet", "Wallet"),
                            ("handshake", "Handshake"),
                            ("gift", "Gift"),
                            ("activity", "Activity"),
                            ("play-circle", "Play Circle"),
                        ],
                        default="heart-pulse",
                        max_length=40,
                    ),
                ),
                ("label", models.CharField(default="Yoga Classes", max_length=80)),
                ("value", models.CharField(default="25+", max_length=20)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Hero Stat Card",
                "verbose_name_plural": "Hero Stat Cards",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="MembershipPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Monthly Plan", max_length=120)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=2999, max_digits=10),
                ),
                ("duration", models.CharField(default="1 Month", max_length=60)),
                (
                    "features",
                    models.TextField(
                        default="Unlimited Yoga Classes\nUnlimited Zumba Sessions\nLocker Access\nFree Nutrition Guide",
                        help_text="One feature per line.",
                    ),
                ),
                (
                    "is_highlighted",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as the Popular / Recommended plan",
                    ),
                ),
                ("cta_text", models.CharField(default="Join Now", max_length=60)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Membership Plan",
                "verbose_name_plural": "Membership Plans",
                "ordering": ["order", "price"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="AURELIA Yoga & Zumba Studio", max_length=120
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        default="Move Your Body. Elevate Your Energy.", max_length=220
                    ),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="branding/"),
                ),
                ("logo_url", models.URLField(blank=True, max_length=500)),
                (
                    "favicon",
                    models.ImageField(blank=True, null=True, upload_to="branding/"),
                ),
                ("favicon_url", models.URLField(blank=True, max_length=500)),
                (
                    "phone_number",
                    models.CharField(default="+91 98765 43210", max_length=40),
                ),
                (
                    "whatsapp_number",
                    models.CharField(default="+91 98765 43210", max_length=40),
                ),
                (
                    "whatsapp_message",
                    models.TextField(
                        default="Hi, I am interested in joining your Yoga/Zumba classes. Please share more details."
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="hello@aureliawellness.com", max_length=254
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        default="42 Wellness Avenue, ECR Road, Chennai, Tamil Nadu, India",
                        max_length=255,
                    ),
                ),
                (
                    "opening_hours",
                    models.CharField(
                        default="Mon – Sat: 5:30 AM – 9:30 PM | Sun: 7:00 AM – 12:00 PM",
                        max_length=255,
                    ),
                ),
                (
                    "google_map_embed_url",
                    models.TextField(
                        default="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3886.589139886364!2d80.2452!3d13.0475!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3a5266497f1f9e53%3A0x6b4f7b21e8d6411!2sChennai%2C%20Tamil%20Nadu!5e0!3m2!1sen!2sin!4v1700000000000"
                    ),
                ),
                (
                    "google_map_direct_url",
                    models.URLField(
                        default="https://maps.google.com/?q=Chennai+Tamil+Nadu",
                        max_length=500,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6, default=13.0475, max_digits=10
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6, default=80.2452, max_digits=10
                    ),
                ),
                (
                    "facebook_url",
                    models.URLField(
                        blank=True, default="https://facebook.com/aureliawellness"
                    ),
                ),
                (
                    "instagram_url",
                    models.URLField(
                        blank=True, default="https://instagram.com/aureliawellness"
                    ),
                ),
                (
                    "youtube_url",
                    models.URLField(
                        blank=True, default="https://youtube.com/@aureliawellness"
                    ),
                ),
                ("twitter_url", models.URLField(blank=True)),
                (
                    "seo_title",
                    models.CharField(
                        default="AURELIA — Premium Yoga & Zumba Studio in Chennai",
                        max_length=200,
                    ),
                ),
                (
                    "seo_description",
                    models.TextField(
                        default="Join AURELIA Yoga & Zumba Studio for premium yoga, Zumba dance fitness, certified trainers, flexible timings and a free trial class."
                    ),
                ),
                (
                    "seo_keywords",
                    models.CharField(
                        default="yoga studio, zumba classes, fitness centre, wellness studio, yoga near me, zumba near me",
                        max_length=400,
                    ),
                ),
                (
                    "og_image",
                    models.ImageField(blank=True, null=True, upload_to="branding/"),
                ),
                ("og_image_url", models.URLField(blank=True, max_length=500)),
            ],
            options={
                "verbose_name": "Website Settings",
                "verbose_name_plural": "Website Settings",
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="testimonials/"),
                ),
                ("photo_url", models.URLField(blank=True, max_length=500)),
                ("rating", models.PositiveSmallIntegerField(default=5)),
                ("review", models.TextField()),
                (
                    "program_joined",
                    models.CharField(
                        blank=True, default="Yoga & Zumba Combo", max_length=150
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Trainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "role",
                    models.CharField(
                        default="Yoga & Wellness Instructor", max_length=150
                    ),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="trainers/"),
                ),
                ("photo_url", models.URLField(blank=True, max_length=500)),
                ("bio", models.TextField(blank=True)),
                ("experience_years", models.PositiveIntegerField(default=5)),
                ("instagram_url", models.URLField(blank=True)),
                ("facebook_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Trainer",
                "verbose_name_plural": "Trainers",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="VideoReel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Morning Flow", max_length=150)),
                ("video", models.FileField(blank=True, null=True, upload_to="reels/")),
                ("video_url", models.URLField(blank=True, max_length=500)),
                (
                    "poster_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="reels/posters/"
                    ),
                ),
                ("poster_image_url", models.URLField(blank=True, max_length=500)),
                ("duration_label", models.CharField(default="0:20", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Short Video Reel",
                "verbose_name_plural": "Short Video Reels",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="WhyChooseFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("heart-pulse", "Heart Pulse"),
                            ("flower-2", "Flower"),
                            ("users", "Users"),
                            ("clock", "Clock"),
                            ("award", "Award"),
                            ("smile", "Smile"),
                            ("sparkles", "Sparkles"),
                            ("shield-check", "Shield Check"),
                            ("dumbbell", "Dumbbell"),
                            ("music-4", "Music"),
                            ("sun", "Sun"),
                            ("leaf", "Leaf"),
                            ("trophy", "Trophy"),
                            ("badge-check", "Badge Check"),
                            ("calendar-check", "Calendar Check"),
                            ("gem", "Gem"),
                            ("target", "Target"),
                            ("wallet", "Wallet"),
                            ("handshake", "Handshake"),
                            ("gift", "Gift"),
                            ("activity", "Activity"),
                            ("play-circle", "Play Circle"),
                        ],
                        default="award",
                        max_length=40,
                    ),
                ),
                (
                    "title",
                    models.CharField(default="Certified Trainers", max_length=120),
                ),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Why Choose Us Feature",
                "verbose_name_plural": "Why Choose Us Features",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ScheduleSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                            ("saturday", "Saturday"),
                            ("sunday", "Sunday"),
                        ],
                        default="monday",
                        max_length=12,
                    ),
                ),
                ("class_name", models.CharField(default="Hatha Yoga", max_length=150)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("yoga", "Yoga"),
                            ("zumba", "Zumba / Fitness"),
                            ("other", "Other"),
                        ],
                        default="yoga",
                        max_length=10,
                    ),
                ),
                ("time", models.CharField(default="6:00 AM – 7:00 AM", max_length=60)),
                ("total_seats", models.PositiveIntegerField(default=20)),
                ("available_seats", models.PositiveIntegerField(default=8)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "trainer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schedule_slots",
                        to="studio.trainer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Weekly Schedule Slot",
                "verbose_name_plural": "Weekly Schedule",
                "ordering": ["order", "day", "id"],
            },
        ),
        migrations.CreateModel(
            name="FitnessProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Zumba Fitness", max_length=150)),
                ("slug", models.SlugField(blank=True, max_length=180, unique=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="programs/fitness/"
                    ),
                ),
                ("image_url", models.URLField(blank=True, max_length=500)),
                (
                    "preview_video",
                    models.FileField(
                        blank=True, null=True, upload_to="programs/fitness/videos/"
                    ),
                ),
                ("preview_video_url", models.URLField(blank=True, max_length=500)),
                ("description", models.TextField(blank=True)),
                ("duration", models.CharField(default="45 mins", max_length=60)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("all-levels", "All Levels"),
                        ],
                        default="all-levels",
                        max_length=20,
                    ),
                ),
                (
                    "schedule",
                    models.CharField(default="Tue, Thu, Sat — 7:00 PM", max_length=150),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=1799, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trainer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fitness_programs",
                        to="studio.trainer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zumba / Fitness Program",
                "verbose_name_plural": "Zumba / Fitness Programs",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="YogaProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Hatha Yoga", max_length=150)),
                ("slug", models.SlugField(blank=True, max_length=180, unique=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="programs/yoga/"
                    ),
                ),
                ("image_url", models.URLField(blank=True, max_length=500)),
                ("description", models.TextField(blank=True)),
                ("duration", models.CharField(default="60 mins", max_length=60)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("all-levels", "All Levels"),
                        ],
                        default="all-levels",
                        max_length=20,
                    ),
                ),
                (
                    "schedule",
                    models.CharField(default="Mon, Wed, Fri — 6:00 AM", max_length=150),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=1999, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trainer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="yoga_programs",
                        to="studio.trainer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yoga Program",
                "verbose_name_plural": "Yoga Programs",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
