# Generated by Django 5.2.17 on 2026-08-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="herocontent",
            name="background_video_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
    ]