# Generated by Django 5.2.17 on 2026-08-21 08:12

import studio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0002_alter_herocontent_background_video_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ctasection",
            name="background_video",
            field=models.FileField(
                blank=True,
                null=True,
                storage=studio.models.video_storage,
                upload_to="cta/videos/",
            ),
        ),
        migrations.AlterField(
            model_name="fitnessprogram",
            name="preview_video",
            field=models.FileField(
                blank=True,
                null=True,
                storage=studio.models.video_storage,
                upload_to="programs/fitness/videos/",
            ),
        ),
        migrations.AlterField(
            model_name="galleryitem",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                storage=studio.models.video_storage,
                upload_to="gallery/videos/",
            ),
        ),
        migrations.AlterField(
            model_name="herocontent",
            name="background_video",
            field=models.FileField(
                blank=True,
                null=True,
                storage=studio.models.video_storage,
                upload_to="hero/videos/",
            ),
        ),
        migrations.AlterField(
            model_name="videoreel",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                storage=studio.models.video_storage,
                upload_to="reels/",
            ),
        ),
    ]